{% set version = "6.2.0" %}

package:
  name: redis-py
  version: {{ version }}

source:
  url: https://github.com/redis/redis-py/archive/v{{ version }}.tar.gz
  sha256: ce5c31c67e00fb1822b3eaa97ddb17d54bf9b1e86c171b5aa9015f4b8bab4169

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - async-timeout >=4.0.3

test:
  commands:
    - pip check
  imports:
    - redis
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/redis/redis-py/
  license: MIT
  license_url: https://github.com/redis/redis-py/blob/master/LICENSE
  license_family: MIT
  license_file: LICENSE
  summary: Python client for Redis key-value store
  description: |
    The Python interface to the Redis key-value store. Requires a running
    Redis server.
  doc_url: https://pypi.python.org/pypi/redis
  doc_source_url: https://github.com/redis/redis-py/blob/master/README.md
  dev_url: https://github.com/redis/redis-py/

extra:
  recipe-maintainers:
    - rxm7706
    - kwilcox
    - daf
